api_platform:
  title: 'Jazzfreunde API'
  description: 'Data access for Jazzfreunde database'
  version: '1.0.0'

  enable_re_doc: false
  mapping:
    paths:
      - '%kernel.project_dir%/src/Api'
  swagger:
    versions: [3]
  formats:
    json:
      mime_types: ['application/json']
    html:
      mime_types: ['text/html']

  error_formats:
    jsonproblem:
      mime_types: ['application/problem+json']

  use_symfony_listeners: true
