/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/already_subscribed_errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a AlreadySubscribedError resource.
         * @description Retrieves a AlreadySubscribedError resource.
         */
        get: operations["api_already_subscribed_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Event resources.
         * @description Retrieves the collection of Event resources.
         */
        get: operations["api_events_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Event resource.
         * @description Retrieves a Event resource.
         */
        get: operations["api_events_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification_subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a NotificationSubscription resource.
         * @description Creates a NotificationSubscription resource.
         */
        post: operations["api_notification_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retry_subscribing_errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a RetrySubscribingError resource.
         * @description Retrieves a RetrySubscribingError resource.
         */
        get: operations["api_retry_subscribing_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlreadySubscribedError: {
            /** @default  */
            readonly message: string;
            /** @default 0 */
            readonly code: number;
            /** @default  */
            readonly file: string;
            /** @default 0 */
            readonly line: number;
            readonly type?: string;
            readonly title?: string | null;
            readonly status?: number | null;
            readonly detail?: string | null;
            readonly instance?: string | null;
            readonly trace?: (string | null)[];
            readonly previous?: components["schemas"]["Throwable"] | null;
            readonly traceAsString?: string;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description API resource for planned events (e.g., concerts, meetings, etc.) */
        Event: {
            id?: number | null;
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            location: components["schemas"]["EventLocation"];
            subtitle?: string | null;
            link?: string | null;
            /**
             * @default none
             * @enum {string}
             */
            category: "none" | "session" | "jazztage" | "jazz-and-literature";
        };
        /** @description API resource for planned events (e.g., concerts, meetings, etc.) */
        "Event.html": {
            id?: number | null;
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            location: components["schemas"]["EventLocation.html"];
            subtitle?: string | null;
            link?: string | null;
            /**
             * @default none
             * @enum {string}
             */
            category: "none" | "session" | "jazztage" | "jazz-and-literature";
        };
        EventLocation: {
            readonly id?: number;
            name: string;
            value?: string;
        };
        "EventLocation.html": {
            readonly id?: number;
            name: string;
            value?: string;
        };
        /** @description Subscription for any type of notifications */
        NotificationSubscription: {
            /** @example /events/123 */
            resourceScope: string;
            /** Format: email */
            email: string;
        };
        /** @description Subscription for any type of notifications */
        "NotificationSubscription.html": {
            /** @example /events/123 */
            resourceScope: string;
            /** Format: email */
            email: string;
        };
        RetrySubscribingError: {
            /** @default  */
            readonly message: string;
            /** @default 0 */
            readonly code: number;
            /** @default  */
            readonly file: string;
            /** @default 0 */
            readonly line: number;
            readonly type?: string;
            readonly title?: string | null;
            readonly status?: number | null;
            readonly detail?: string | null;
            readonly instance?: string | null;
            readonly trace?: (string | null)[];
            readonly previous?: components["schemas"]["Throwable"] | null;
            readonly traceAsString?: string;
        };
        Throwable: {
            readonly message?: string;
            readonly code?: unknown;
            readonly file?: string;
            readonly line?: number;
            readonly trace?: (string | null)[];
            readonly previous?: components["schemas"]["Throwable"] | null;
            readonly traceAsString?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_already_subscribed_errors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description AlreadySubscribedError resource */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["AlreadySubscribedError"];
                    "application/json": components["schemas"]["AlreadySubscribedError"];
                };
            };
        };
    };
    api_events_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                /** @description The number of items per page */
                itemsPerPage?: number;
                "start[before]"?: string;
                "start[strictly_before]"?: string;
                "start[after]"?: string;
                "start[strictly_after]"?: string;
                "order[start]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                    "text/html": components["schemas"]["Event.html"][];
                };
            };
        };
    };
    api_events_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                    "text/html": components["schemas"]["Event.html"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_notification_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new NotificationSubscription resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSubscription"];
                "text/html": components["schemas"]["NotificationSubscription.html"];
            };
        };
        responses: {
            /** @description NotificationSubscription resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSubscription"];
                    "text/html": components["schemas"]["NotificationSubscription.html"];
                };
            };
            /** @description Already subscribed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["AlreadySubscribedError"];
                    "application/json": components["schemas"]["AlreadySubscribedError"];
                };
            };
        };
    };
    api_retry_subscribing_errors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description RetrySubscribingError resource */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RetrySubscribingError"];
                    "application/json": components["schemas"]["RetrySubscribingError"];
                };
            };
        };
    };
}
